language: python

python:
  - '3.7'

branches:
  only:
    - master

install:
  - pip install docker==3.7.3 docker-compose molecule PyYAML==3.13 requests==2.20.1

jobs:
  include:
    - stage: test
      script:
        - ansible --version
        - molecule --version
        - pip freeze
        - cd ansible/test--docker-compose--compose--create.role && molecule test
