language: python

python:
  - '3.7'

branches:
  only:
    - master

install:
  - pip3 install molecule docker==3.7.3 docker-compose

jobs:
  include:
    - stage: test
      script:
        - ansible --version
        - molecule --version
        - pip3 freeze
        - cd ansible/test--docker-compose--compose--create.role && molecule test
