language: python

python:
  - '3.7'

branches:
  only:
    - master

install:
  - pip install docker==3.7.3 docker-compose molecule requests==2.20.1
  - ls -Al /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages

jobs:
  include:
    - stage: test
      script:
        - cd ansible/test--docker-compose--compose--create.role && molecule test
