dist: bionic

language: python

python:
  - '3.7'

services:
  - docker

branches:
  only:
    - master

sudo: required

before_install:
  - deactivate

install:
  - lsb_release -a
  - docker --version
  - docker-compose --version
  - python --version
  - python3 --version
  - pip install --user ansible molecule
  - ansible --version
  - molecule --version

jobs:
  include:
    - stage: test
      script:
        - cd ansible/test--docker-compose--compose--create.role && molecule test
