dist: bionic

language: minimal

services:
  - docker

branches:
  only:
    - master

sudo: required

before_install:
  - sudo apt-get update && sudo apt-get install --no-install-recommends --yes build-essential python3 python3-pip python3-setuptools

install:
  - pip3 install --user ansible docker==3.7.3 molecule requests==2.20.1 wheel

jobs:
  include:
    - stage: test
      script:
        - cd ansible/test--docker-compose--compose--create.role && molecule test
