dist: bionic

language: python

python:
  - '3.7'

services:
  - docker

branches:
  only:
    - master

install:
  - lsb_release -a
  - docker --version
  - docker-compose --version
  - python --version
  - python3 --version
  - pip install ansible docker==3.7.3 molecule requests==2.20.1
  - ansible --version
  - molecule --version

jobs:
  include:
    - stage: test
      script:
        - cd ansible/test--docker-compose--compose--create.role && molecule test
