language: python

python:
  - '3.7'

branches:
  only:
    - master

install:
  - pip install --user docker==3.7.3 docker-compose molecule

jobs:
  include:
    - stage: test
      script:
        - ansible --version
        - molecule --version
        - python --version
        - python3 --version
        - pip --version
        - pip3 --version
        - pip freeze
        - cd ansible/test--docker-compose--compose--create.role && molecule test
