---
- name: prepare_command
  command: /bin/bash bash-util/elevate.sh root bash-commands/docker-compose--compose--create.sh . default.docker-compose
  args:
    chdir: "{{ test_dir }}"
  notify: execute_command

- name: execute_command
  command: /bin/bash bash-util/elevate.sh root bash-commands/docker-compose--container--restart.sh . default.docker-compose
  args:
    chdir: "{{ test_dir }}"
