---
- name: cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: remove_docker_container
      docker_container:
        name: server--draw-io
        state: absent
    - name: remove_tests_directory
      file:
        group: "{{ lookup('env','USER') }}"
        mode: 0o700
        owner: "{{ lookup('env','USER') }}"
        path: ../../../../tests
        state: absent
  vars:
    ansible_python_interpreter: /usr/bin/python3
